run:
  timeout: 10m

  # Run linters over integration tests
  build-tags:
    - integration

linters:
  disable-all: true # Disable defaults, then enable the ones we want
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    # - structcheck https://github.com/golangci/golangci-lint/issues/2649
    - typecheck
    - unused
    # - bodyclose Disabled so concurrent GETs can happen
    - stylecheck
    - gosec
    - goimports
    - gci
